git add ./Assets/Scripts/
git add ./Assets/Scenes/
git add ./Assets/Settings/
git add ./Assets/Materials/
git add ./Packages/
git add ./ProjectSettings/
git add ./.gitignore
git add ./.vsconfig
git add ./README.md
git add ./Unity.gitattributes
git add ./Unity.gitignore
git add ./miniGolVR_add.sh
